version: "3.4"

services:
  tinyurl:
    image: tinyurl:latest
    container_name: "tinyurl-02-server"
    restart: always
    ports:
      - "6600:6600"
    networks:
      - deployments_network-tinyurl
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://127.0.0.1:12201"
        tag: "tinyurl"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
        reservations:
          memory: 2G

networks:
    deployments_network-tinyurl:
      external: true
