version: "3.4"

services:
  mysql-exporter:
    image: prom/mysqld-exporter
    container_name: "tinyurl-03-mysql-exporter"
    restart: always
    ports:
      - "9104:9104"
    environment:
      DATA_SOURCE_NAME: 'exporter:123456@(mysql:3306)/tinyurl'
    networks:
      - deployments_network-tinyurl
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
        reservations:
          memory: 512M

  redis-exporter:
    image: oliver006/redis_exporter
    container_name: "tinyurl-03-redis-exporter"
    restart: always
    ports:
      - "9121:9121"
    networks:
      - deployments_network-tinyurl
    command:
      - "--redis.addr=redis://redis:6379"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
        reservations:
          memory: 512M

  prometheus:
    image: prom/prometheus
    container_name: "tinyurl-03-prometheus"
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    networks:
      - deployments_network-tinyurl
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
        reservations:
          memory: 512M
    depends_on:
      - mysql-exporter

  grafana:
    image: grafana/grafana
    container_name: "tinyurl-03-grafana"
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    networks:
      - deployments_network-tinyurl
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
        reservations:
          memory: 512M
    depends_on:
      - prometheus

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: "tinyurl-03-jaeger"
    restart: always
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
      COLLECTOR_OTLP_ENABLED: true
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
        reservations:
          memory: 512M
    networks:
      - deployments_network-tinyurl

networks:
    deployments_network-tinyurl:
      external: true