version: "3.4"

services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: "tinyurl-mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "0"
      MYSQL_DATABASE: "tinyurl"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    networks: 
      - network-tinyurl
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 4G

  redis:
    image: redis:latest
    container_name: "tinyurl-redis"
    restart: always
    ports:
      - 6379:6379
    networks:
      - network-tinyurl
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 4G

networks:
    network-tinyurl:
      driver: bridge

