version: "3.4"

services:
  tinyurl:
    image: tinyurl:latest
    container_name: "tinyurl-02-server"
    restart: always
    ports:
      - "6600:6600"
    networks:
      - deployment_network-tinyurl
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://172.19.0.16:12201"
        tag: "tinyurl"

networks:
    deployment_network-tinyurl:
      external: true
