version: "3.4"

services:
  locust:
    image: locustio/locust
    container_name: "tinyurl-04-locust"
    restart: always
    networks:
      - deployment_network-tinyurl
    ports:
     - "8089:8089"
    volumes:
      - ./data/locust:/mnt/locust
    command: --config=/mnt/locust/locust.conf

networks:
  deployment_network-tinyurl:
    external: true
