global:
  scrape_interval:     5s # 多久獲取一次目標
  evaluation_interval: 15s # 多久評估一次規則

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

    - job_name: 'mysql-exporter'
    static_configs:
    - targets: ['mysql-exporter:9104']