name: golanci-lint
on:
  push:
    branches:
      - main
jobs:
  golangci:
    strategy:
      matrix:
        go: [1.18]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/setup-go@v3
        with: 
          go-version: ${{matrix.go}}
      - uses: actions/checkout@v3
      - uses: golanci/golangci-lint-action@v3
        with:
          version: v1.50